/**
 * Runtime application configuration contract.
 *
 * Loaded from `/config.json` at startup by {@link ConfigService} via `APP_INITIALIZER`.
 * In production, `/config.json` is generated by the container entrypoint script from
 * actual environment variables before the app is served.
 *
 * @example Container entrypoint (envsubst pattern):
 * ```sh
 * envsubst < /usr/share/nginx/html/config.template.json \
 *           > /usr/share/nginx/html/config.json
 * ```
 */
export interface AppConfig {
  /**
   * Full origin of the backend API.
   * Maps to the container env var `BACKEND_URL`.
   * @example 'https://ductifact-staging-api.jcapsule.work'
   */
  BACKEND_URL: string;

  /**
   * JWT validity window in milliseconds.
   * Must mirror the backend `JWT_TOKEN_DURATION` setting.
   * Maps to the container env var `TOKEN_EXPIRY_MS`.
   * @example 900000 (= 15 minutes)
   */
  TOKEN_EXPIRY_MS: number;

  /**
   * Base URL for MinIO S3 object-storage assets (bucket endpoint).
   * Maps to the container env var `FILE_STORAGE_URL`.
   * @example 'https://ductifact-staging-api.jcapsule.work/storage/ductifact'
   */
  FILE_STORAGE_URL: string;
}
