import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';
import type { AppConfig } from './config.model';

/** Declarative rule describing how a single config key must be validated. */
interface FieldRule<T> {
  /** Expected JavaScript `typeof` for the parsed JSON value. */
  type: 'string' | 'number';
  /**
   * Format validator — invoked only when the type check passes.
   * @param {T} value - The typed, non-null value to validate.
   * @returns {boolean} `true` if the value satisfies the format constraint.
   */
  validate(value: T): boolean;
  /** Human-readable correction hint printed in the bootstrap error. */
  hint: string;
}

/**
 * Maps every `AppConfig` key to its validation rule.
 * Adding a new key to `AppConfig` without adding a rule here is a compile error.
 */
type ValidationSchema = { [K in keyof AppConfig]: FieldRule<AppConfig[K]> };

const SCHEMA: ValidationSchema = {
  BACKEND_URL: {
    type: 'string',
    /**
     * Validates that the value is a well-formed http(s) URL.
     * @param {string} v - The raw string value from the config payload.
     * @returns {boolean} `true` if the value matches the `http(s)://` pattern.
     */
    validate: (v) => /^https?:\/\/.+/.test(v),
    hint: 'Must be a valid http(s) URL  →  e.g. https://api.example.com',
  },
  FILE_STORAGE_URL: {
    type: 'string',
    /**
     * Validates that the value is a well-formed http(s) URL.
     * @param {string} v - The raw string value from the config payload.
     * @returns {boolean} `true` if the value matches the `http(s)://` pattern.
     */
    validate: (v) => /^https?:\/\/.+/.test(v),
    hint: 'Must be a valid http(s) URL  →  e.g. https://storage.example.com/bucket',
  },
};

/**
 * Loads and validates runtime configuration from `/config.json` before the
 * application bootstraps. Registered exclusively via `APP_INITIALIZER` in
 * `app.config.ts` — do not call `load()` manually.
 *
 * In production, `/config.json` is generated by the container entrypoint from
 * actual environment variables. For local development, edit `public/config.json`.
 */
@Injectable({ providedIn: 'root' })
export class ConfigService {
  private readonly http = inject(HttpClient);
  private config: AppConfig | null = null;

  /**
   * Fetches `/config.json`, runs the full validation schema against every key,
   * and stores the result. Invoked exclusively by `APP_INITIALIZER` — guaranteed
   * to complete before any component or service reads config values.
   * @returns {Promise<void>} Resolves when the config is loaded and fully valid.
   * @throws {Error} If any key is absent, has the wrong type, or fails format validation.
   */
  async load(): Promise<void> {
    const raw = await firstValueFrom(this.http.get<Record<string, unknown>>('/config.json'));
    this.validate(raw);
    this.config = raw as unknown as AppConfig;
  }

  /**
   * Returns the value of a runtime config key.
   * Safe to call only after {@link load} has resolved (i.e. after app bootstrap).
   * @template K
   * @param {K} key - The config key to retrieve.
   * @returns {AppConfig[K]} The runtime value for the requested key.
   * @throws {Error} If called before {@link load} completes.
   */
  get<K extends keyof AppConfig>(key: K): AppConfig[K] {
    if (!this.config) {
      throw new Error(`[ConfigService] get("${key}") called before load() completed.`);
    }
    return this.config[key];
  }

  /**
   * Runs the full declarative schema against the raw JSON payload.
   * Collects every error before throwing so developers see all issues at once
   * rather than discovering them one per restart.
   * @param {Record<string, unknown>} raw - The raw parsed JSON object from `/config.json`.
   * @returns {void}
   * @throws {Error} If one or more keys are missing, wrongly typed, or fail format validation.
   */
  private validate(raw: Record<string, unknown>): void {
    const errors: string[] = [];

    for (const key of Object.keys(SCHEMA) as (keyof AppConfig)[]) {
      const rule = SCHEMA[key] as FieldRule<unknown>;
      const value = raw[key];

      if (value === undefined || value === null || value === '') {
        errors.push(`  • ${key}  [MISSING]\n    → ${rule.hint}`);
        continue;
      }

      if (typeof value !== rule.type) {
        errors.push(
          `  • ${key}  [WRONG TYPE — got "${typeof value}", expected "${rule.type}"]\n` +
            `    → ${rule.hint}`,
        );
        continue;
      }

      if (!rule.validate(value)) {
        errors.push(`  • ${key}  [INVALID VALUE — "${value}"]\n    → ${rule.hint}`);
      }
    }

    if (errors.length === 0) return;

    const bar = '─'.repeat(66);
    const msg = [
      `\n${bar}`,
      ` [ConfigService]  APPLICATION BOOTSTRAP ABORTED`,
      ` ${errors.length} configuration error(s) found in /config.json`,
      bar,
      ...errors,
      bar,
      ` HOW TO FIX:`,
      `   Local dev  →  edit  public/config.json`,
      `   Container  →  ensure the entrypoint writes /config.json from ENV vars`,
      `${bar}\n`,
    ].join('\n');

    console.error(msg);
    throw new Error(
      `[ConfigService] Bootstrap aborted — ${errors.length} config error(s). See console for details.`,
    );
  }
}
